### ISSUE TITLE
load dataset fails 

### ISSUE THREAD

**Issue by eghbalhosseini** [brain-score/language#66]
trying to load Pereira dataset in the test and I get the following error :

Traceback (most recent call last):
  `File "<input>", line 1, in <module>
  File "/brain-score-language/brainscore_language/__init__.py", line 29, in load_dataset
    return data_registry[identifier]()
  File "/brain-score-language/brainscore_language/data/pereira2018/__init__.py", line 20, in <lambda>
    data_registry['Pereira2018.language'] = lambda: load_from_s3(
  File "/brain-score-language/brainscore_language/utils/s3.py", line 35, in load_from_s3
    file_path = fetch_file(location_type="S3",
TypeError: fetch_file() got an unexpected keyword argument 'version_id'
`
 `fetch_file` is a brainio function as far as I can tell

**Comment by mschrimpf** [comment]
Hi @eghbalhosseini, I think the issue is that you're on an older version of brainio. Can you please `pip uninstall brainio` and then reinstall with `pip install "brainio@git+https://github.com/brain-score/brainio.git@main"`?

**Comment by mschrimpf** [comment]
assuming this is resolved, please reopen if not
